name: Multiple-Jobs
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Build
        run: echo "Deploy build"
