name: Multiple-Jobs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: echo "Build Successfully"
      - name: Run tests
        run: echo "Test Successfully"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Build
        run: echo "Deploy build"
